# Generated by Django 4.2.7 on 2023-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_phonenumber_user_alter_user_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='чужой инвайт-код'),
        ),
    ]
