# Generated by Django 4.2.7 on 2023-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_user_friend_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='инвайт-код от друга'),
        ),
    ]
