# Generated by Django 4.2.7 on 2023-11-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время подтверждения'),
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='last_sending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней отправки'),
        ),
    ]
